import React from 'react';
import styles from '../styles/About.module.css';
import Head from 'next/head';


const About = () => {
      return (
            <>
                  <Head>
                        <title>Create Next App by afride</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <meta name="keyword" content="afride nextjs react" />
                        <link rel="icon" href="/favicon.ico" />
                  </Head>

                  <main className={styles.main}>
                        <h1 className={styles.title}>This is about page</h1>
                        <p className={styles.description}>
                              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maiores a omnis hic at nam dolor, iure enim doloremque porro, numquam veniam facilis! Pariatur quasi dignissimos impedit nemo aperiam cumque perspiciatis dolores voluptates praesentium corporis doloremque deleniti alias, ratione maxime at molestiae unde reprehenderit, dolor provident commodi? Explicabo officia illo esse placeat quas aspernatur saepe sequi non aut, libero porro rerum facilis vitae enim a possimus! Possimus totam repellendus cumque nam cum similique autem aut dolorum, molestiae ullam delectus ratione accusantium iste nemo earum. Eligendi esse ipsum nulla libero reprehenderit porro veritatis, obcaecati voluptate sit, explicabo, velit aliquid? Quisquam inventore iste est numquam? Quibusdam eaque nihil laboriosam enim, temporibus maxime cum! Ab, vitae eveniet necessitatibus itaque aliquam porro, impedit consequuntur ullam dolorem exercitationem soluta laborum maxime, et perspiciatis? Alias ipsa animi nulla reiciendis rerum aspernatur minus! Voluptates, minima esse itaque consequuntur ipsum quam vel. Necessitatibus quasi perferendis numquam, laudantium quis aliquam accusamus itaque aspernatur, ratione a dolore, aperiam officiis officia sequi asperiores. Alias ratione repellat aspernatur hic libero necessitatibus. Autem debitis rem minus, quo totam eveniet quas, inventore assumenda non esse aliquam tempora recusandae eius repudiandae quaerat? Itaque voluptatibus blanditiis debitis aliquid, sunt illo aperiam dicta ipsum veritatis repellendus accusamus minus modi dolorum quisquam natus nisi placeat facilis exercitationem ab molestias quos animi. Minima, ut repudiandae. Saepe expedita eveniet voluptatem tempore aliquid natus dolore culpa qui non laudantium laboriosam cum praesentium dolores soluta atque nulla asperiores ipsum amet, ea repellendus rerum libero corporis quis. A ea quaerat similique fuga accusantium saepe assumenda, ut voluptatem porro vel doloremque vero dolorum optio amet eveniet exercitationem. Consequuntur ratione nesciunt illum magni laboriosam rem labore ab cupiditate itaque numquam ducimus fugiat consectetur sint distinctio aut officiis, modi at vel. Cupiditate sint error possimus expedita inventore perferendis quas vitae? Fugiat cupiditate ipsum, minima aliquam omnis magnam ullam odio, odit laborum voluptatibus, reiciendis pariatur itaque magni soluta perspiciatis! Non quas dicta quos omnis perspiciatis aliquam laudantium dolores nihil ipsam. Dolor quis qui autem laudantium ullam illo consequuntur sint necessitatibus ab tempore impedit consequatur minima soluta perferendis quod inventore laboriosam facilis dignissimos quasi unde mollitia totam, placeat officia! Exercitationem itaque repudiandae fugit omnis dicta accusantium nisi aperiam libero sapiente deserunt, et adipisci unde praesentium, quod magni eius hic debitis deleniti vero, sequi ipsam minima. Maxime ab dolorum nulla accusamus, quod repellat esse quibusdam. Odit voluptatibus necessitatibus rem numquam amet voluptas magnam recusandae mollitia beatae libero, aperiam quod quo, dicta eligendi, excepturi dolores ex quidem itaque architecto maiores! Sapiente, necessitatibus delectus quo ullam ducimus vero fugit, dolore fuga eius laborum consequuntur officia fugiat cupiditate corporis harum, ea repellendus quidem quae exercitationem quasi neque. Ducimus nesciunt eligendi vero, expedita nulla voluptas, impedit molestiae laborum quos iure voluptatum at animi ipsam dolor! Laborum maxime voluptatem est facilis molestias facere, rerum expedita ipsa suscipit, illo, vero reiciendis! Odio, eos iure qui possimus sed fugiat. Provident dolorum veritatis minus distinctio asperiores, impedit quos assumenda voluptatem cum animi reprehenderit, nisi non obcaecati autem? Iste nisi dolor tenetur beatae voluptates ad iure quod velit deleniti!
                        </p>
                  </main>
            </>
      );
};

export default About;